feat: waiting message during recovery.
logion-network/logion-wallet pull request #204
Opened 2022-02-03 16:06 UTC by benoitdevos

logion-network/logion-internal#326

2022-02-03 16:12 UTC, gdethier requested changes
Great job! Just a couple of suggestions and one change.

2022-02-03 16:12 UTC, gdethier commented on src/common/TransactionConfirmation.test.tsx
> +fdescribe("TransactionConfirmation", () => {
remove the `f`.

2022-02-03 16:12 UTC, gdethier commented on src/common/TransactionConfirmation.test.tsx
> +    test("goes to status TRANSFERRING upon start", () => {
Don't we use `it` in the other tests?

2022-02-03 16:16 UTC, benoitdevos commented on src/common/TransactionConfirmation.test.tsx
> +fdescribe("TransactionConfirmation", () => {
Done.

2022-02-03 16:17 UTC, benoitdevos commented on src/common/TransactionConfirmation.test.tsx
> +    test("goes to status TRANSFERRING upon start", () => {
Yes, of course. Done.

2022-02-04 07:24 UTC, gdethier approved these changes
:+1:

2022-02-04 08:18 UTC, merged